import os
os.makedirs("my_project/src", exist_ok=True)
os.makedirs("my_project/docs", exist_ok=True)
os.makedirs("my_project/data", exist_ok=True)
open("my_project/src/main.py", "w").close()
open("my_project/docs/README.md", "w").close()
open("my_project/data/input.txt", "w").close()
print("Thu muc my_project chua:")
print(os.listdir("my_project"))
print("\nThu muc src:")
print(os.listdir("my_project/src"))
print("\nThu muc docs:")
print(os.listdir("my_project/docs"))
print("\nThu muc data:")
print(os.listdir("my_project/data"))